<?php

namespace backend\controllers;

use backend\models\ContactsAssignment;
use backend\models\ContactsLog;
use backend\models\UserModel;
use common\helper\Helper;
use common\models\User;
use Yii;
use backend\models\ContactsModel;
use backend\models\ContactsSearchModel;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * ContactsController implements the CRUD actions for ContactsModel model.
 */
class ContactsController extends BaseController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ContactsModel models.
     * @return mixed
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }


    public function actionIndex()
    {
        $phone = Yii::$app->request->get("phone");
        if (Helper::userRole(UserModel::_ADMIN) && !$phone) {
            $this->redirect(Url::toRoute(['/contacts-assignment/index']));
        }
        if (Helper::userRole(UserModel::_SALE)) {
            $saleID = Yii::$app->user->getId();
            $phone = UserModel::findOne($saleID);
            $phone = $phone->processing->contact_phone;
        }

        $searchModel = new ContactsSearchModel();
        $dataProvider = $searchModel->search(array_merge(
            Yii::$app->request->queryParams,
            [
                'ContactsSearchModel' => [
                    'phone' => $phone,
                    'status' => [
                        ContactsModel::_NEW,
                        ContactsModel::_PENDING,
                        ContactsModel::_CALLBACK,
                    ]
                ]
            ]
        ));
        $failureProvider = $searchModel->search(array_merge(
            Yii::$app->request->queryParams,
            [
                'ContactsSearchModel' => [
                    'phone' => $phone,
                    'status' => [
                        ContactsModel::_CANCEL,
                        ContactsModel::_SKIP,
                        ContactsModel::_DUPLICATE,
                        ContactsModel::_NUMBER_FAIL
                    ]
                ]
            ]
        ));
        $successProvider = $searchModel->search(array_merge(
            Yii::$app->request->queryParams,
            [
                'ContactsSearchModel' => [
                    'phone' => $phone,
                    'status' => ContactsModel::_OK
                ]
            ]
        ));

        $modelNote = new ContactsLog;
        $info = ContactsModel::find(['phone' => $phone])->groupBy('phone')->one();

        $log =  $this->actionSubmit();
        if(Yii::$app->request->isPost){
            if($log){
                self::success("Thành công!");
            }else{
                self::error("Lôii");
            }
        }
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'failureProvider' => $failureProvider,
            'successProvider' => $successProvider,
            'modelNote' => $modelNote,
            'info' => $info
        ]);
    }

    function actionSubmit()
    {
        if (Yii::$app->request->isPost) {
            $log = new ContactsLog;
            if ($log->load(Yii::$app->request->post())) {
                if ($log->save()) {
                    return true;
                }
            }
            return false;
        }
    }

    /**
     * Displays a single ContactsModel model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ContactsModel model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ContactsModel();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ContactsModel model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ContactsModel model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ContactsModel model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ContactsModel the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ContactsModel::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
