<?php


namespace backend\controllers;


use backend\models\AuthAssignment;
use backend\models\ContactsModel;
use backend\models\LandingPages;
use backend\models\ProductsModel;
use backend\models\UserModel;
use common\helper\Helper;
use yii\helpers\ArrayHelper;

class PartnerController extends BaseController
{
    public $partnerName;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $user = \Yii::$app->user->identity->username;
        $this->partnerName = $user;
    }

    public function actionIndex()
    {

        return $this->render('index',[
            'partner' => $this->partnerName
        ]);
    }

    public function actionOrderDetail()
    {
        return $this->render('order',[
            'partner' => $this->partnerName
        ]);
    }

    public function actionFinance()
    {
        return $this->render('finance',[
            'partner' => $this->partnerName
        ]);
    }

    public function actionWarehouse()
    {
        return $this->render('warehouse',[
            'partner' => $this->partnerName
        ]);
    }
}