<?php


namespace backend\modules\controllers;


use backend\models\ContactsModel;

class ContactsController extends DefaultController
{
    public $modelClass = ContactsModel::class;

    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

}