<?php


namespace backend\modules\controllers;


use backend\models\ContactsModel;
use common\helper\Helper;

class ContactsController extends DefaultController
{
    public $modelClass = ContactsModel::class;

    public function actions()
    {
        $actions =  parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['create']);
        return $actions;
    }
    public function actionCreate(){
        if(\Yii::$app->request->isPost){
            $data = \Yii::$app->request->post();
            $model = new ContactsModel();
            $model->scenario = ContactsModel::SCENARIO_API;

            if($model->load($data, '')){
                if(!$model->save($data)){
                    return Helper::firstError($model);
                }
            }
        }
        return  [
            'status' => 201,
            'message' => 'Success!'
        ];
    }

}