<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "backups".
 *
 * @property int $id
 * @property string|null $name
 * @property int $created_at
 * @property int $updated_at
 */
class Backups extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'backups';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'string'],
            [['name'], 'required'],
            [['created_at', 'updated_at'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên file',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Ngày cập nhật',
        ];
    }
    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        unlink(Yii::getAlias("@backups"). "/". $this->name);
    }

    public function afterFind()
    {
        $this->created_at = date('d/m/Y H:i:s');
        parent::afterFind(); // TODO: Change the autogenerated stub
    }
}
