<?php

namespace backend\models;

use cakebake\actionlog\model\ActionLog;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "categories".
 *
 * @property int $id
 * @property string $name
 * @property string $description
 * @property int $created_at
 * @property int $updated_at
 */
class CategoriesModel extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'categories';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['created_at', 'updated_at'], 'integer'],
            [['name', 'description'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    static function select()
    {
        $all = self::find()->all();
        return ArrayHelper::map($all, 'id', 'name');
    }

    public function getSku()
    {
        return $this->hasMany(ProductsModel::className(), ['category_id' => 'id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            ActionLog::add("success", "Tạo danh mục khoản mới $this->name");
        }
        ActionLog::add("success", "Cập nhật danh mục $this->name");
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        ActionLog::add("success", "Xóa danh mục $this->username");
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
