<?php


namespace backend\models;


use mdm\admin\models\form\ChangePassword;

class ChangePass extends ChangePassword
{
    public function __construct($config = [])
    {
        parent::__construct($config);
    }

    public function rules()
    {
        return [
            [['oldPassword', 'newPassword', 'retypePassword'], 'required'],
            [['oldPassword'], 'validatePassword'],
            [['newPassword'], 'string', 'min' => 4],
            [['retypePassword'], 'compare', 'compareAttribute' => 'newPassword'],
        ];
    }

    public function validatePassword()
    {
        parent::validatePassword(); // TODO: Change the autogenerated stub
    }
    public function change()
    {
        return parent::change(); // TODO: Change the autogenerated stub
    }

}