<?php

namespace backend\models;

use common\helper\Helper;
use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "contacts_log_import".
 *
 * @property int $id
 * @property string $name
 * @property string $phone
 * @property string|null $email
 * @property string|null $address
 * @property int|null $zipcode
 * @property string|null $option
 * @property string|null $ip
 * @property string|null $note
 * @property string|null $link
 * @property string|null $short_link
 * @property string|null $utm_source
 * @property string|null $utm_medium
 * @property string|null $utm_content
 * @property string|null $utm_term
 * @property string|null $utm_campaign
 * @property string|null $host
 * @property string|null $hashkey
 * @property string|null $status
 * @property int $created_at
 * @property int $updated_at
 * @property int $callback_time
 * @property int $code
 * @property string|null $country
 * @property int|null $register_time
 */
class ContactsLogImport extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public $email;

    public static function tableName()
    {
        return 'contacts_log_import';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['phone'], 'required', 'message' => '{attribute} không được để trống!'],
            [['address', 'option', 'link', 'short_link', 'code', 'note', 'country', 'type', 'reason_msg'], 'string'],
            [['register_time'], 'safe'],
            [['zipcode', 'created_at', 'updated_at', 'callback_time'], 'integer'],
            [['name', 'reason', 'utm_source', 'utm_medium', 'utm_content', 'utm_term', 'utm_campaign', 'host', 'hashkey'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 15],
            [['email'], 'string', 'max' => 100],
            //[['hashkey'], 'unique', 'message' => 'Liên hệ đã tồn tại với lựa chọn option tương ứng!'],
            [['ip', 'status'], 'string', 'max' => 50],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function beforeSave($insert)
    {
        if ($insert) {
            if (!$this->created_at) {
                $this->created_at = time();
            }

            $maxIDNumber = ContactsModel::find()->max('id');
            if (!$maxIDNumber) {
                $maxIDNumber = ContactsLogImport::find()->max('id');
            }
            if (!$maxIDNumber) {
                $maxIDNumber = 0;
            }

            $this->short_link = Helper::getHost($this->link);
            $this->hashkey = md5($this->phone . $this->short_link . $this->option);
            $this->host = Helper::getHost(Yii::$app->request->getHostInfo());

            $this->country = $this->country ? $this->country : Helper::findCountryFromZipcode($this->zipcode, $this->link);

            $this->code = (!$this->code || !strpos($this->code, $this->country)) ? Helper::makeCodeIncrement($maxIDNumber, $this->country) : $this->code;

            $this->register_time = empty($this->register_time) ? time() : Helper::convertTime($this->register_time);

//            if (self::checkExists($this->hashkey)) {
//                $this->addError("hashkey", "Liên hệ đã tồn tại với lựa chọn option tương ứng!");
//                return false;
//            }
//            if (self::checkExistCapture($this->phone, $this->short_link)) {
//                $this->addError("type", "Liên hệ đã tồn tại với phân loại capture form!");
//                return false;
//            }

        } else {
            if (!$this->option) {
                $this->addError("option", "Không để trống yêu cầu đặt hàng!");
                return false;
            }
            if (!$this->link) {
                $this->addError("option", "Không để trống trang đích!");
                return false;
            }
        }
        $this->updated_at = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    static function checkExists($haskey)
    {
        if (self::findOne(['hashkey' => $haskey])) {
            return true;
        }
        return false;
    }

    static function checkExistCapture($phone, $link)
    {
        $count = self::find()->where(['phone' => $phone, 'short_link' => $link])
            ->andFilterWhere(['LIKE', 'type', self::_CAPTURE])->count();
        if ($count > 0) {
            return true;
        }
        return false;
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'phone' => 'Phone',
            'code' => 'Code',
            'address' => 'Address',
            'zipcode' => 'Zipcode',
            'category' => 'Category',
            'option' => 'Option',
            'customer_note' => 'Customer Note',
            'status' => 'Status',
            'note' => 'Note',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function getContact()
    {
        return $this->hasOne(ContactsModel::className(), ['phone' => 'phone']);
    }

    public function getLog()
    {
        return $this->hasOne(ContactsLog::className(), ['phone' => 'phone', 'contact_code' => 'code']);
    }

    public function getPage()
    {
        return $this->hasOne(LandingPages::className(), ['link' => 'short_link'])->with('category');
    }
}
