<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "contacts_log".
 *
 * @property int $id
 * @property int $user_id
 * @property int $contact_id
 * @property string|null $status
 * @property string $note
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Contacts $contact
 * @property User $user
 */
class ContactsLog extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'contacts_log';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'contact_id','status'], 'required'],
            [['user_id', 'contact_id', 'created_at', 'updated_at'], 'integer'],
            [['status'], 'string', 'max' => 50],
            [['note'], 'string', 'max' => 255],
            [['contact_id'], 'exist', 'skipOnError' => true, 'targetClass' => ContactsModel::className(), 'targetAttribute' => ['contact_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => UserModel::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'contact_id' => 'Contact ID',
            'status' => 'Status',
            'note' => 'Note',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[Contact]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getContact()
    {
        return $this->hasOne(ContactsModel::className(), ['id' => 'contact_id']);
    }
    public function beforeSave($insert)
    {
        if($insert){
            $contact = ContactsModel::findOne($this->contact_id);
            $contact->status = $this->status;
            $contact->save();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(UserModel::className(), ['id' => 'user_id']);
    }
}
