<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "form_info".
 *
 * @property int $id
 * @property int|null $category_id
 * @property string|null $content
 * @property float|null $revenue
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Categories $category
 * @property FormInfoSku[] $formInfoSkus
 */
class FormInfo extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'form_info';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id', 'created_at', 'updated_at'], 'integer'],
            [['revenue'], 'number'],
            [['category_id', 'revenue', 'content'], 'required'],
            [['content'], 'string', 'max' => 255],
            //[['content'], 'unique'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => CategoriesModel::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Category ID',
            'content' => 'Content',
            'revenue' => 'Revenue',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[Category]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(CategoriesModel::className(), ['id' => 'category_id']);
    }

    /**
     * Gets query for [[FormInfoSkus]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function beforeSave($insert)
    {
        $this->content = trim($this->content);

        if ($insert) {
            $exitst = FormInfo::find()->where([
                'content' => $this->content,
                'category_id' => $this->category_id
            ])->one();
            if ($exitst) {
                $this->addError("content", "Đã tồn nội dung với danh mục trên!");
                return false;
            }
        } else {
            $exitst = FormInfo::find()->where([
                'content' => $this->content,
                'category_id' => $this->category_id
            ])->andWhere(['<>', 'id', $this->id])->one();
            if ($exitst) {
                $this->addError("content", "Đã tồn nội dung với danh mục trên!");
                return false;
            }
        }


        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getSkus()
    {
        return $this->hasMany(FormInfoSku::className(), ['info_id' => 'id']);
    }
    public function getContacts(){
        return $this->hasMany(ContactsModel::className(), ['option' => 'content'])->groupBy(['option']);
    }
}
