<?php

namespace backend\models;

use cakebake\actionlog\model\ActionLog;
use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "products".
 *
 * @property int $id
 * @property string $name
 * @property string $sku
 * @property float|null $regular_price
 * @property float|null $sale_price
 * @property int|null $category_id
 * @property string|null $description
 * @property string|null $option
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Categories $category
 */
class ProductsModel extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'products';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'sku', 'category_id'], 'required'],
            [['regular_price', 'sale_price'], 'number'],
            [['category_id', 'created_at', 'updated_at'], 'integer'],
            [['name', 'sku', 'description'], 'string', 'max' => 255],
            [['sku'], 'unique'],
            [['option'], 'string'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => CategoriesModel::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Tên sản phẩm',
            'sku' => 'Mã sản phẩm',
            'regular_price' => 'Giá gốc',
            'sale_price' => 'Giá giảm',
            'category_id' => 'loại sản phẩm',
            'description' => 'Mô tả',
            'option' => 'Tùy chọn',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[Category]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(CategoriesModel::className(), ['id' => 'category_id'])->with('sku');
    }

    public function getStorage()
    {
        return $this->hasOne(WarehouseStorage::className(), ['product_sku' => 'sku'])->with('transaction');
    }

    public function getOrderItems()
    {
        return $this->hasOne(OrdersItems::className(), ['product_sku' => 'sku'])->addSelect([
            'product_sku',
            'SUM(qty) as pending'
        ]);
    }

    static function select($val = "id", $view = "name")
    {
        $all = self::find()->all();

        return ArrayHelper::map($all, $val, $view);
    }

    public function beforeSave($insert)
    {
        $this->regular_price = empty($this->regular_price) ? 0 : $this->regular_price;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            ActionLog::add("success", "Tạo sản phẩm $this->name");
        }
        ActionLog::add("success", "Cập nhật sản phẩm $this->name");
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        ActionLog::add("success", "Xóa sản phẩm $this->name");
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
