<?php

namespace backend\models;


use common\helper\Helper;
use common\models\User;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use mdm\admin\models\Assignment;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $username
 * @property string $auth_key
 * @property string $password_hash
 * @property string|null $password_reset_token
 * @property string $email
 * @property int $status
 * @property int $created_at
 * @property int $updated_at
 * @property string|null $verification_token
 *
 * @property LandingPages[] $landingPages
 */
class UserModel extends User
{
    /**
     * {@inheritdoc}
     */
    public $role;
    const _ADMIN = 'admin';
    const _SALE = 'sale';
    const _MARKETING = 'marketing';
    const _LADING = 'lading';
    const _WAREHOUSE = 'warehouse';


    const STATUS = [
        parent::STATUS_ACTIVE => 'Kích hoạt',
        parent::STATUS_INACTIVE => 'Chưa kích hoạt',
        parent::STATUS_DELETED => 'Tạm dừng',
    ];

    static function label($status)
    {
        switch ($status) {
            case self::STATUS_DELETED:
                return Html::tag("span", ArrayHelper::getValue(self::STATUS, $status), ['class' => 'badge badge-danger']);
                break;
            case self::STATUS_INACTIVE:
                return Html::tag("span", ArrayHelper::getValue(self::STATUS, $status), ['class' => 'badge badge-secondary']);
                break;
            default:
                return Html::tag("span", ArrayHelper::getValue(self::STATUS, $status), ['class' => 'badge badge-success']);
                break;
        }
    }

    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'password_hash', 'email', 'role'], 'required'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['role', 'username', 'password_hash', 'password_reset_token', 'email', 'verification_token'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['email'], 'email'],
            [['password_reset_token'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Tên đăng nhập',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Mật khẩu',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'status' => 'Trạng thái',
            'created_at' => 'Ngày tạo',
            'updated_at' => 'Updated At',
            'verification_token' => 'Verification Token',
        ];
    }

    /**
     * Gets query for [[LandingPages]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getLandingPages()
    {
        return $this->hasMany(LandingPages::className(), ['user_id' => 'id']);
    }

    public function setPassword($password)
    {
        parent::setPassword($password); // TODO: Change the autogenerated stub
    }

    public function generateAuthKey()
    {
        return parent::generateAuthKey(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        if ($insert) {
            $this->auth_key = Yii::$app->security->generateRandomString();
            $this->setPassword($this->password_hash);
        }

        return parent::beforeSave($insert);
    }

    public function afterSave($insert, $changedAttributes)
    {
        $auth = new Assignment($this->id);
        $auth->assign([$this->role]);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        $auth = new Assignment($this->id);
        $auth->revoke(array_keys(ArrayHelper::getValue($auth->getItems(), 'assigned')));
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

    public function getRole()
    {
        return $this->hasOne(AuthAssignment::class, ['user_id' => 'id']);
    }

    public function getProcessing()
    {
        return $this->hasOne(ContactsAssignment::className(), ['user_id' => 'id'])->where(['contacts_assignment.status' => ContactsAssignment::_PROCESSING]);
    }

    public static function hasCallback()
    {
        $model = ContactsAssignment::find()->where(['user_id' => Yii::$app->user->getId()])->orderBy(['callback_time' => SORT_ASC])->one();
        if (!empty($model->callback_time)) {
            return Helper::caculateDate($model->updated_at, $model->callback_time);
        }
        return false;
    }
}
