<?php

namespace backend\models;

use common\helper\Helper;
use Yii;
use yii\base\Model;

/**
 * This is the model class for table "zipcode_country".
 *
 * @property int $id
 * @property string|null $country_code
 * @property string $country_name
 * @property string $zipcode
 * @property string $city
 * @property string|null $district
 * @property string|null $address
 * @property int $created_at
 * @property int $updated_at
 */
class ZipcodeCountry extends BaseModel
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'zipcode_country';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['country_code', 'zipcode', 'city'], 'required'],
            [['created_at', 'updated_at'], 'integer'],
            [['country_code'], 'string', 'max' => 10],
            [['country_name', 'city', 'district', 'address'], 'string', 'max' => 255],
            [['zipcode'], 'string', 'max' => 15],
            [['zipcode'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function beforeSave($insert)
    {
        $this->country_name = Helper::getCountry($this->country_code);

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'country_code' => 'Country Code',
            'country_name' => 'Country Name',
            'zipcode' => 'Zipcode',
            'city' => 'City',
            'district' => 'District',
            'address' => 'Address',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
}
